redis:
    image: redis:alpine
    ports: ["6379"]
    
pdf_to_text:
    build: ./pdf_to_text/
    command: nodemon -L --debug=5858
    volumes:
        - ./pdf_to_text:/app
    ports:
        - "3000:3000"
        - "5858:5858"
    links:
        - ocr_service

luis_adapter_service:
    build: ./luis_adapter_service/
    command: nodemon -L --debug=5858
    volumes:
        - ./luis_adapter_service:/app
    ports:
        - "3001:3000"
        - "5859:5858"
    environment: 
        - LuisAppId=5e5610fe-0f83-4058-882a-08977872d91e
        - LuisSubscriptionKey=${LuisSubscriptionKey}

ocr_service:
    build: ./ocr_service/
    ports: 
        - "5001:5000"
    command: host
    environment:
        - ComputerVisionKey="${ComputerVisionKey}"